# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27977c0fcd11de3ac918f3073f6dbd5b73f2e8de35826cb4347df7ff212e2daa41989c74ff2fd309b612afb6c3e3ef112d2e55c9a07f3424c64ee14e1dec6126

test:
  secret_key_base: ec7e03eebe77a7572360f2a94d9fa0c7948f68c5c00a59e47fdc53e63d694a9d8560097eaf3d4ae2504b55f9288228d53e677553b20636eeef83e21bc51a1e33

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
